In [1]:
import numpy as np
from numpy import array as Matriz
from numpy import linalg as Modulo
pi = np.pi
#Determinando o valor de Epsilon:
eps0 = 1e-9/(36*pi)

Três cargas pontuais $ 𝑄_1 = 1𝑚𝐶, 𝑄_2 = 2𝑚𝐶$ e $𝑄_3 = −3𝑚𝐶$ estão localizadas em $(0,0,4), (−2,6,1)$ e $
(3, −4, −8)$ respectivamente. Determine:

a) A força sobre $Q_1$ 

In [2]:
#Determinando os valores das cargas especificados na questão
q1 = 1e-3
q2 = 2e-3
q3 = -3e-3
#Determinando as posições das 3 cargas
r1 = Matriz([0,0,4])
r2 = Matriz([-2,6,1])
r3 = Matriz([3,-4,-8])


In [30]:
Q = q1/(4*pi*eps0)
r12 = r1-r2
R12 = (Modulo.norm(r12))**3
R12
r13 = r1-r3
R13 = (Modulo.norm(r13))**3

A = (q2*r12)/(R12)
B = (q3*r13)/(R13)

In [31]:
F = Q*(A+B)
F

array([ 141.82472521, -364.02674731,    9.96057439])

In [17]:
r12 = r2-r1
R12 = Modulo.norm(r12)
a12 = r12/R12
a12

array([-0.28571429,  0.85714286, -0.42857143])

A força total em Q1 é:
[ -68.08781123  265.71086202 -304.90823028]


7.0

b) O campo elétrico (E) em $(4,2,2)$

In [34]:
p = Matriz([4,2,2])
#Vetores posição
r1p = p-r1
r2p = p-r2
r3p = p-r3
#Distancias dos 3 pontos menos o ponto p
d1p = Modulo.norm(r1p)**3
d2p = Modulo.norm(r2p)**3
d3p = Modulo.norm(r3p)**3

#Campo elétrico E
E1 =  (q1*r1p)/(4*pi*eps0)*d1p
E2 = (q2*r2p)/(4*pi*eps0)*d2p
E3 = (q3*r3p)/(4*pi*eps0)*d3p
#Campo total
Et = E1+E2+E3
Et

array([ 2.60838231e+09, -2.85438650e+11, -4.28127984e+11])

c) O potencial elétrico em $(4,2,2)$

In [60]:
#Potencial Elétrico das 3 cargas

V1 = (1/4*pi*eps0) * q1/ Modulo.norm(r1p)
V2 = (1/4*pi*eps0) * q2/ Modulo.norm(r2p)
V3 = (1/4*pi*eps0) * q3/ Modulo.norm(r3p)

#Potencial elétrico Total
V_t = V1+V2+V3

print (V_t)

1.5454026098213985e-15


d)O trabalho necessário para mover uma carga pontual de $1mC$ de $(4,2,2)$ a $(5,2,2)$